### ISSUE TITLE
Flutter integration test page does not mention the requirement for an x server to be running on the machine

### ISSUE THREAD

**Issue by af-chacon** [flutter/website#10464]
### Page URL

https://docs.flutter.dev/testing/integration-tests

### Page source

https://github.com/flutter/website/blob/main/src/content/testing/integration-tests/index.md

### Describe the problem

Upon attempting to run integration tests on github actions I ran into an issue where the command `flutter test integration_test -d linux -r github` would fail due to there not being a debugger to connect to.

![image](https://github.com/flutter/website/assets/139920357/9980fc39-4728-4711-8572-2f1dd8b4e2ff)

After many attempts at getting this running, I found an obscure reference that the command above requires the existence of an x-server on Linux.

The following worked:
```yml
      - name: Run Integration Tests
        uses: smithki/xvfb-action@v1.1.2
        with:
          run: flutter test integration_test -d linux -r github
```
The usage of xvfb-run is required in CI using Linux and this is not documented.  

### Expected fix

Please add a reference to requiring an x-server running on linux for the integration_test to work.
Additionally, a working example of a github actions yml would be helpful for future users of this feature.

Here is an example of this:
```yml
name: Flutter Web Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  setup:
    name: Setup & Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Start Web Release Build
        run: flutter build linux

      - name: Run Unit Tests
        run: flutter test

      - name: Run Integration Tests
        uses: smithki/xvfb-action@v1.1.2
        with:
          run: flutter test integration_test -d linux -r github
```

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.
