### ISSUE TITLE
Letter 'f' is missing.

### ISSUE THREAD

**Issue by bjorn-avans** [flutter/website#11189]
### Page URL

https://docs.flutter.dev/ui/layout/tutorial/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/layout/tutorial.md

### Describe the problem

The letter 'f' is missing in front of 'lutter' in the following code block:

```
lutter:
 uses-material-design: true
 assets:
   - images/lake.jpg
```

### Expected fix

Add the letter 'f' in front of 'lutter' to make the code block complete.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.
