### ISSUE TITLE
[Container image] consider: change gem path, and cache bundle gems

### ISSUE THREAD

**Issue by chalin** [flutter/website#1202]
I think that we should probably cache gems along the lines of the [Cirrius doc example](https://cirrus-ci.org/examples/#ruby). Something like this:

```yaml
website_task:
  ...
  setup_script: ./tool/setup.sh
  bundle_cache:
    folder: # *** I'm not sure what the right path is, see below ***
    fingerprint_script: ruby -v && cat Gemfile.lock
    populate_script: bundle update
```

(And a similar entry would need to be added for the `deploy_website_task` task.)

I'm not sure what the path to the gem folder is. It seems to be `/var/lib/gems/<ruby-version>/gems`. Actually, according to the [How to use Bundler with Docker](https://bundler.io/v1.16/guides/bundler_docker_guide.html#how-to-use-bundler-with-docker) page, we should be using these environment variables:

```dockerfile
ENV GEM_HOME="/usr/local/bundle"
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH
```

I'm hoping that resolving this issue will allow PRs to have altered Gemfiles, which will be processed before testing the PR.

cc @Sfshaza
