### ISSUE TITLE
Clarify how to combine Fastlane Flutter and Travis CI

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/website#1749]
The point 3 of chapter "Cloud build and deploy setup" of this side: https://flutter.io/docs/deployment/fastlane-cd
Should be explained much more detailed here: https://docs.fastlane.tools/getting-started/cross-platform/flutter/

I have totally no idea how to setup flutter fastlane and travis combined.

FYI: https://github.com/fastlane/docs/issues/739

**Comment by HerrNiklasRaab** [comment]
I think, we should explain, the basic setup of a travis.yml and cirrus.yml. For cirrus.yml it is a little bit easier to understand because of the example, but I use travis in my projekt. And i need to search the whole web and pick some information from everywhere. I am now 2 Days in this search for information scenario. It is trial and error at the moment.

If extra explaining is to too much, at least i need a running example with Travis CI + Flutter + Fastlane + IOS + Android.

**Comment by janpio** [comment]
So you [local setup](https://flutter.io/docs/deployment/fastlane-cd#local-setup) is fully working (as the article advises before moving over to CI) and just the CI/Travis part is not working for you?

**Comment by HerrNiklasRaab** [comment]
Yes, correct! How do i set up Travis.yml for IOS and Android. This is my current approach: 
```
matrix:
  include:
  - os: linux
    language: android
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-27
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-android-support
    install:
    - cd android
    - bundle install
    script:
    - echo "flutter.sdk=../../flutter/" >> local.properties
    - bundle exec fastlane beta
before_install:
- openssl aes-256-cbc -K $encrypted_94197833ced1_key -iv $encrypted_94197833ced1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- gem install bundler
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
- ./flutter/bin/flutter doctor
- ./flutter/bin/flutter packages get
- yes | sdkmanager "platforms;android-27"
```

It is totally trial and error to get this running. If i had examples it would be better.
