### ISSUE TITLE
Doc on how to use fonts from Google Fonts directly

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1822]
@xster commented on [Fri Dec 01 2017](https://github.com/flutter/flutter/issues/13292)

Not clear from https://flutter.io/custom-fonts/ whether it's the right practice is to download the font from Google Fonts first and then add them locally to the Flutter project or whether CDN hosted font files can be cached and managed by the pub mechanism directly.

---

@xster commented on [Fri Dec 01 2017](https://github.com/flutter/flutter/issues/13292#issuecomment-348427699)

Doesn't seem to work if I just add
```
  fonts:
    - family: Nunito
      fonts:
        - asset: https://fonts.gstatic.com/s/nunito/v9/ZvK1I6E_n0tqLlSfX5iQt4X0hVgzZQUfRDuZrPvH3D8.woff2
```
to pubspec.yaml
