### ISSUE TITLE
'Testing Flutter apps' page issue

### ISSUE THREAD

**Issue by AJ9** [flutter/website#2167]
Page URL: https://flutter.io/docs/testing/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/index.md

Description:

The tutorial for integration testing is missing the `test` dependency. 

The `Adding the flutter_driver dependency` section should specify this: 

```
dev_dependencies:
  test:
  flutter_driver:
    sdk: flutter
```
