### ISSUE TITLE
Codelab DartPads should inject code, not use gists

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4104]
Details: https://github.com/dart-lang/site-www/issues/2421

Let's figure out the best way to fix these before going all in.

**Comment by sfshaza2** [comment]
I used a script-based embedded DartPad on some pages and found it to be super easy!

**Comment by kwalrath** [comment]
Can you point to the pages where you did that? (Unless that's more work than just doing it. :)

**Comment by sfshaza2** [comment]
I was afraid you'd ask...  I'm trying to remember....

I REMEMBER! It was when I added the [Understanding constraints](https://flutter.dev/docs/development/ui/layout/constraints) page.

I added this JavaScript pieces to the front matter:

```
---
title: Understanding constraints
description: Flutter's model for widget constraints, sizing, positioning, and how they interact.
toc: false
js:
  - defer: true
    url: https://dartpad.dev/inject_embed.dart.js
---
```

And then you add this to the markdown file:

```
```run-dartpad:theme-light:mode-flutter:run-true:width-100%:height-600px:split-60:ga_id-starting_code
// CODE GOES HERE
``` (ending tick marks)
```

And, of course, you can tweak the parameters for the DartPad itself. That's it!!!  To see the actual markdown, check out [constraints.md](https://raw.githubusercontent.com/flutter/website/master/src/docs/development/ui/layout/constraints.md).
