### ISSUE TITLE
'Adding assets and images' page issue

### ISSUE THREAD

**Issue by KenChoi1992** [flutter/website#5209]
Page URL: https://flutter.dev/docs/development/ui/assets-and-images.html
Page source: https://github.com/flutter/website/blob/master/src/docs/development/ui/assets-and-images.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
You're not describe how to load assets files like JSON from **packages**, I just checking my `pubspec.yaml` again and again!
Please add how to load assets files from packages to the document.
```
var content = await rootBundle.loadString('packages/[package name]/assets/[JSON file name]);
```
package's `pubspec.yaml` :
```
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/data.json
```
