### ISSUE TITLE
'Handle scrolling' page issue

### ISSUE THREAD

**Issue by XenLabsNikhil** [flutter/website#5944]
Page URL: https://flutter.dev/docs/cookbook/testing/integration/scrolling.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/integration/scrolling.md

Description of issue: 

scrollUntilVisible example given here is deprecated.

I have added integration test dependancy as given in this URL: https://flutter.dev/docs/testing/integration-tests

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```
