### ISSUE TITLE
[PAGE ISSUE]: 'An introduction to integration testing'

### ISSUE THREAD

**Issue by TheVinhLuong** [flutter/website#6926]
### Page URL

https://docs.flutter.dev/cookbook/testing/integration/introduction/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/testing/integration/introduction.md

### Describe the problem

The doc instructs me to add dependencies like this but it is not working:
```
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
```

### Expected fix

Define as this works for me
```
dev_dependencies:
  integration_test:
  flutter_test:
    sdk: flutter
```
