### ISSUE TITLE
Document that iOS and macOS plugin code can be shared in the same directory

### ISSUE THREAD

**Issue by jmagman** [flutter/website#8486]
### What information is missing?

Flutter now supports `sharedDarwinSource` key in the pubspec for plugins to indicate that iOS and macOS code should be shared.

```yml
      ios:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderFoundation
        sharedDarwinSource: true
```
https://github.com/flutter/packages/blob/519408398687d3338d97cc80290bb440c880972b/packages/path_provider/path_provider_foundation/pubspec.yaml#L15-L22

Design doc at https://flutter.dev/go/plugin-shared-ios-macos

Implemented in https://github.com/flutter/flutter/pull/115337

cc @stuartmorgan 

### How would you like us to fix this problem?

Update the following sections
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2e-add-macos-platform-code-swift
