### ISSUE TITLE
Create a new design document index and process

### ISSUE THREAD

**Issue by parlough** [flutter/website#8749]
I've been seeing a few mentions for increased visibility and discovery of design documents as Flutter developers want to better understand areas being explored or provide their own feedback.

We have https://docs.flutter.dev/resources/design-docs but that is just an alphabetically ordered list with little value.

Could we introduce a process of not only adding a redirect, but perhaps adding to a YAML file with the go link, a short description, author, product/focus area, date, etc. Then we can render that information with more information that is ordered, categorized, searchable, etc. This file could be added to in the same PR as when the redirect is added.

```yaml
- title: Flutter blank canvas custom controls
  id: blankcanvas
  description: > 
    Lower the cost for people to create high-quality bespoke widget sets, 
    whether to better fit their brand identity, 
    further differentiate themselves from competing apps, 
    or just to add whimsy.
  authors:
    - Hixie
  date: 2022-11-18
  areas:
    - framework
    - widgets
    - api
```

**Questions:** Do you think this would be valuable? Worth the little extra work? What information do you think would be useful to include?
